service: test
plugins:
  - ../src

custom:
  documentation:
    api:
      info: ${file(./swagger/objects/info.yml)}
      tags: ${file(./swagger/objects/tags.yml)}

package:
  individually: true # 각 함수 별로 패키징 하도록 설정
  excludeDevDependencies: true

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  logRetentionInDays: 90
  region: ${self:custom.REGION.${self:provider.stage}.${param:area}}
  stage: ${opt:stage, 'predev'}

  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}

functions:
  theRouter:
    handler: handler.router
    events:
      - http:
          path: example/message
          method: get
          cors: true
          documentation:
            summary: Gets a simple message
            tags:
              - Tag1
            description: >
              Demonstrates a GET method. You can see query string parameters,
              request headers, response body and response headers.
            queryParams:
              - name: firstParam
                description: The first param that we want, you MUST pass it
                required: true
              - name: secondParam
                description: The second param. This one is optional
            methodResponses:
              - statusCode: '200'
                responseModels:
                  'application/json': MessageResponse
                responseHeaders:
                  - name: link
                    description: describes other actions that can be taken
                    type: string
  #- ${file(src/business/function.yml)}
  #- ${file(src/dashboard/function.yml)}
  #- ${file(src/openapi/function.yml)}
